### ISSUE TITLE
Plugins is missing

### ISSUE THREAD

**Issue by czipperz** [jinput/jinput#1]
Cloned the repos onto my computer and was looking at the source code, when an error came up. The repository doesn't contain the "Plugins" class that is used in DefaultControllerEnvironment.

**Comment by Endolf** [comment]
It comes from JUtils https://java.net/projects/jutils, available in maven http://search.maven.org/#artifactdetails%7Cnet.java.jutils%7Cjutils%7C1.0.0%7Cjar

**Comment by czipperz** [comment]
Thanks!
