### ISSUE TITLE
Can only detect Flightstick

### ISSUE THREAD

**Issue by SvenWollinger** [jinput/jinput#132]
Im running Windows 11, tested with java 19 and 8, i got these devices:
Keyboard (USB)
Xbox One Controller (Bluetooth)
Mouse (Bluetooth)
Flighstick (USB)

Using the example code here:
https://github.com/jinput/jinput/blob/master/examples/src/main/java/net/java/games/input/example/ReadAllEvents.java
Only the flightstick is detected.
If i unplug it, i get no events.
Im not sure where to go from here.

When using the stick my output looks like this:
`Extreme 3D pro at 562976390000000, Z Rotation changed to 0.063492775`
`Extreme 3D pro at 562976390000000, Z Rotation changed to 0.055558085`
`Extreme 3D pro at 562976390000000, Z Rotation changed to 0.063492775`
`Extreme 3D pro at 562976390000000, Z Rotation changed to 0.055558085`
`Extreme 3D pro at 562976390000000, Z Rotation changed to 0.047623396`
`Extreme 3D pro at 562976390000000, Z Rotation changed to 0.039688706`

The Xbox Controller (which im trying to target) is being detected and the buttons are all there, but no events are triggered with the example code.
Any ideas?

**Comment by SvenWollinger** [comment]
Okay the issue is gone if i open a simple JFrame window.
is there any way to make this run without that? Id like it to control the mouse without a window in focus

**Comment by Valkryst** [comment]
You might want to try using [XInput-Plugin-for-JInput](https://github.com/RalleYTN/XInput-Plugin-for-JInput), though I haven't personally used it. The README seems to indicate that there are known issues with XBox gamepads, and that the library resolves them
