### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by manteka** [jinput/jinput#169]
JInput does not work with Windows 11

feb 25, 2024 4:28:18 P. M. net.java.games.input.DefaultControllerEnvironment getControllers
ADVERTENCIA: Found unknown Windows version: Windows 11
feb 25, 2024 4:28:18 P. M. net.java.games.input.DefaultControllerEnvironment getControllers
ADVERTENCIA: Attempting to use default windows plug-in.

**Comment by Endolf** [comment]
What version are you using?

**Comment by manteka** [comment]
2.0.9. Just realised 2.0.10 is released. Will try it. Give me 5 minutes. 

Thank you.

**Comment by Endolf** [comment]
That'd do it :)
