### ISSUE TITLE
Add/Remove listeners are not called.

### ISSUE THREAD

**Issue by googol42** [jinput/jinput#17]
Hello,

OS: Archlinux
JInput: 2.0.7
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
Using these two controllers: https://www.amazon.de/CSL-Gamepad-Controller-Notebook-Retro-Design/dp/B00HFQEFTY/

I tried to add my own listeners for adding/removing controllers. But they are never called. My example code can be found here: https://gist.github.com/googol42/2b59998d9a96b7b10dbd25f73168c2e5

Also getControllers on the environment does not update when removing or adding a controller. It seems that this is not working or did I overlook anything?

Regards

PS: Thanks for the new release 👍

**Comment by Endolf** [comment]
That is correct, all controllers need to be plugged in before launching an application.
