### ISSUE TITLE
Unhandled exception in RawMouseInfo when mouse button count >= 32.

### ISSUE THREAD

**Issue by cjritola** [jinput/jinput#179]
When a mouse (real or not) registers with more than 32 buttons, as found in [this bug](https://github.com/jtrfp/terminal-recall/issues/248), [plugins/windows/java/net/java/games/input/RawMouseInfo.java](https://github.com/jinput/jinput/blob/master/plugins/windows/src/main/java/net/java/games/input/RawMouseInfo.java) breaks with an uncaught exception.

The idea of a mouse with more than 31 buttons is preposterous, but input is input. We never figured out what caused this anomaly on the end-user's machine's firmware:

1. `num_buttons` exceeds 31
2. `DIIdentifierMap.getButtonIdentifier(int))` gets passed a value greater than 31.
3. ... unable to map using its switch block, said method defaults and returns null, which is passed into `IdentifierMap.mapMouseButtonIdentifier(...)`, which again fails to categorize this value and returns the null
4. The null is then passed to Component.Identifier.Button id = ...
5. ... such that null is passed to the 2nd parameter of new `RawMouse.Button(device, id, i);`
6.` RawMouse.Button() `constructor throws NPE due to `id.getName() `where `id==null`.

Proposed kludge is to clamp num_buttons to the range [0,31] in the `RawMouseInfo()` constructor before storing to the class field. This seems to work when overriding that file in my project with a custom one in my local repo.

**Comment by Endolf** [comment]
Should be fixed in 2.0.11-SNAPSHOT as part of PR #180
