### ISSUE TITLE
Cannot rumble two motors on gamepad 

### ISSUE THREAD

**Issue by harlock76** [jinput/jinput#2]
Hello,

I tried to use JInput to rumble my gamepad's motors,
but I dont feel any difference in my hands, just as if only the right motor was turning (also it does not turns smoothly, it feels jerky)

gamepad is a Dragon Shock (dragonwar.eu) on windows 7

I tested the gamepad with the control pannel tester, and both motors work, so I am wondering if JInput really works at all

    ControllerEnvironment cEnvironment = ControllerEnvironment.getDefaultEnvironment();
    Controller[] cControllers = cEnvironment.getControllers();

    if (cControllers.length>0)
    {
        for (int i = 0; i < cControllers.length; i++) 
        {
              if (cControllers[i].getType() == Controller.Type.GAMEPAD) 
              {
                  System.out.println ("Controller Name: " + cControllers[i].getName()+" Type: " + (cControllers[i].getType())+" Rumble: " + ((cControllers[i].getRumblers().length > 0) ? "Yes" : "No"));

                  for (int o = 0; o < cControllers[i].getRumblers().length; o++) 
                  {
                      System.out.println ("- Rumbling Axis: " + cControllers[i].getRumblers()[o].getAxisName());
                      cControllers[i].getRumblers()[o].rumble(1.0f);
                      Thread.Sleep(5000);
                      cControllers[i].getRumblers()[o].rumble(0.0f);
                      Thread.Sleep(2000);
                  }
              }
        }
    }

any advice ?

thanks

**Comment by harlock76** [comment]
hello ??

**Comment by Endolf** [comment]
I don't have access to one of those gamepads. Last time I used rumblers in JInput I had access to a logitech wingman device. On that one, there are 2 motors inside, they seemed to be associated with rumbling at different levels, one would run for values less than 50% and both for more than that if I recall correctly. Try rumbling at various levels rather than just on and off and see if there is any change.

**Comment by harlock76** [comment]
I thought about that but then I thought no way... ok I'll give it a try..thanks

**Comment by Endolf** [comment]
I was surprised too, but it's all directx gave us when querying, it's also what the linux version does using evdev, so I think it's at a driver/hardware level rather than anything we do in JInput

**Comment by harlock76** [comment]
I tried values from 0.0 to 5.0, both motors are rumbling at the same time (I unscrewed the back cover to check the motors while testing)
one again if I use windows control panel I can rumble motors independently

**Comment by harlock76** [comment]
also if it detects 5 rumblers(only have two in the gamepad) getAxisIdentifier() and rumbler.getAxisName() return null

**Comment by Endolf** [comment]
Without access to this particular device I can't resolve the specifics. Generally JInput is a fairly simple wrapper around whatever the OS presents us. If directx reports 5 rumblers with no axis association that's exactly what we pass on to JInput API users. Control panel might make some assumptions that are not listed in the API docs for directx about certain devices, but nothing that I've seen.

**Comment by harlock76** [comment]
yep, I am trying to find some directx powered app that I could test to see if I have the same issue
