### ISSUE TITLE
Can you please revert the change in Java target back to java 8 for the released binaries on Maven?

### ISSUE THREAD

**Issue by madhephaestus** [jinput/jinput#218]
There seems to be no new features in the JVM that are actually used in this project. Some larger applications are stuck at java 8 (Class file version 52) for the foreseeable future. There should be no problem changing this for folks with newer java systems, Java is fully backwards compatible. Making this change would allow the updates (Specifically the M1 updates) to be pulled into applications that can not at this time update to a newer version of java.

**Comment by madhephaestus** [comment]
Are there any known objections to using Java 8 as the compilation target?

**Comment by Valkryst** [comment]
You may have to wait some time for Endolf to check it out, as he's the only maintainer (AFAIK). Recently, it seems like he pops-in every month or-so to handle the Dependabot PRs, so it may take a while

**Comment by madhephaestus** [comment]
On Jan 28 @Endolf made the change and this broke compatibility with BowlerStudio

**Comment by Endolf** [comment]
There are 2 options here, One is to revert the changes, the other is to pass the java source and compile versions as properties to build for Java 8 as a secondary build, which is tempting as Java 8 is obsolete, having a build as a backup might work for those who really are stuck.

**Comment by madhephaestus** [comment]
Azul has official support for Java 8 through 2030, which incidentally is a longer support horizon than for 17, the version currently targeted. https://www.azul.com/products/azul-support-roadmap/
My application is stuck on java 8 until there is a change to the way the private assets in javafx are harmonized in DockFX. In the meantime i would like to add M1 support for game controllers. Besides, targeting an earlier classfile version can be done in the latest JVM, so the support horizon doesn't even come into play. Since there are no class file features in the latest version, changing the targeted support to match the existent feature-set is more correct than updating the target without reason. The intention with having classfile target be independent of the jvm used (the CI is using Java 21 to target 17, or in my case 8) is to encode the utilized JVM features into a compiler level detection (class file version number).  The targeted version should reflect the source-code compatibility, not the latest supported jvm. I agree that you should keep the jvm used to compile the source fully up to date, but the target version is a very different thing. 

And again, targeting the java version that the source is written in (8)  just allows supported jvm's to use it, in addition to newer ones. It does not change the compatibility with newer jvms at all.
