### ISSUE TITLE
Turn into Maven project

### ISSUE THREAD

**Issue by leif81** [jinput/jinput#22]
I see there's a `maven` branch where some work was started. What's the status of that branch and is it likely it'll get merged in?

**Comment by Endolf** [comment]
If I recall that branch got as far as the java code building, but didn't build the native code. I did ponder using the ant maven plugin so the main build was a maven build that called out to ant to build the native code but didn't really see much point. The project would still depend on ant and can currently be declared as maven dependency when used by other projects. Unless you have a particular use case that has been overlooked?

**Comment by leif81** [comment]
Ah I see. Ya, well, that's not half bad actually. I'm a fan of Maven `pom.xml` based projects because of how well Maven projects are supported by Netbeans, etc. Or maybe I've just gotten lazy and prefer not figuring out how everyone's custom ant targets work 😜 

So ya if your branch gets the Java part of the library building with Maven I still think that's a really worth while thing getting merged.

**Comment by dyorgio** [comment]
Maven is not a replacement for ANT, there is no problem to have a maven project using maven-ant-plugin to call ant script (external or inside pom).
Turning project to maven will improve it standardization. More easy to just download source and build.

**Comment by Endolf** [comment]
Fixed in PR #29
