### ISSUE TITLE
Couldn't find the "net.java.games.util.plugins" folder with the .java files inside it

### ISSUE THREAD

**Issue by masarapmabuhay** [jinput/jinput#248]
Hallo,

I was able to compile the `jinput-2.0.10.jar` and the `jinput-2.0.10-natives-all.jar` files along with my code, but received the following error:

## --

<img width="960" alt="sfzErrorJInputV20240724" src="https://github.com/user-attachments/assets/18c5e2e4-afe5-482b-8017-846a4500ab71">

## --

It appears that I'm compiling using an earlier version of the JDK. 

I understand that "version 61.0" pertains to `JDK 17`. 

https://openjdk.org/projects/jdk/17/

Currently, I'm using `OpenJDK 1.8`, but may eventually use the even earlier `OpenJDK 1.7` to upload the app on Steam.

I browsed through jinput's source code on GitHub, but couldn't find the `net.java.games.util.plugins` folder and the `.java` files inside it.

May I ask if the `.java` files are still available? Or are the `.class` files the only ones that remain?

Thank you.

Michael

**Comment by Valkryst** [comment]
Hi, Michael,

It looks like you're trying to use version [2.0.10](https://github.com/jinput/jinput/releases/tag/2.0.10) which updated the minimum required Java version to 17.

There was a [recent PR](https://github.com/jinput/jinput/pull/219) which, after a bit of discussion, reverted the minim required Java version to 8.

If you're using a build system (e.g. Maven, Gradle, etc...), then we need to ask @Endolf to release a new version with the changes above and you'll need to update to that release.

However, if you're building the JARs on your own, you can pull the latest changes to the `master` branch, recompile with the appropriate Java version, and it should work.

**Comment by Endolf** [comment]
The java utils plugin code is [here](https://github.com/jinput/jutils).

**Comment by masarapmabuhay** [comment]
Valkryst and Endolf,

Thank you for the replies.

I was able to successfully compile the code, albeit with deprecation warnings, among others, using the java utils plugin code from the link that Endolf provided.

I note that there's another set of files from jinput-master\plugins\windows that needs to be included.

I understand that the Java app still has to be re-compiled based on the target operating system using jinput. 

I am now working on solving the "java.lang.UnsatisifiedLinkError: no jinput-dx8 in java.library.path" that appears when I run the app on Windows. 

Meanwhile, thanks again and cheers!

Michael
