### ISSUE TITLE
Anyone got it working with gradle?

### ISSUE THREAD

**Issue by elect86** [jinput/jinput#27]
As title, I'm trying to get it working under Window with the following line

    dependencies {
        compile 'net.java.jinput:jinput:2.0.7'
        compile 'net.java.jinput:jinput-platform:2.0.7:natives-windows'

But the natives are still missing...

> java.lang.UnsatisfiedLinkError: no jinput-dx8_64 in java.library.path

What am I doing wrong?

**Comment by Endolf** [comment]
Have you unpacked the natives jar and set the java.library.path to where you have located them?

There is a maven plugin that does that work for you, I've not tried Gradel myself.

**Comment by monsieurmax** [comment]
Hello dear elect.

here's how I do it : 
```
compile 'net.java.jinput:jinput-platform:2.0.7'
compile 'net.java.jinput:jinput:2.0.7'
```
and then I extract the natives during packaging
copy {
    from zipTree(destFolder.toString() + "/lib/jinput-platform-2.0.7-natives-windows.jar")
    into destFolder.toString() + "/lib"
 }

**Comment by elect86** [comment]
> Have you unpacked the natives jar and set the java.library.path to where you have located them?

Shall I do that manually? With lwjgl natives everything is automatic..

@monsieurmax this:
`setProperty("java.library.path", Paths.get("lib").toAbsolutePath().toString());`
won't completely replace the path with the given one?

**Comment by monsieurmax** [comment]
Well, it'll probably replace it, but that's something expected in my own scenario.
For other similar purposes I use env. variables.

In any case, this is working perfectly for my games and on thousands of computers.

Do you still got some issues after setting this up ?

**Comment by elect86** [comment]
it's not working

```            String javaPath = System.getProperty("java.library.path");
            String jInputNativesLocation = Paths.get("lib/jInput/").toAbsolutePath().toString();
            String newJavaPath = javaPath + ";" + jInputNativesLocation;
            System.setProperty("java.library.path", newJavaPath);```

Looking at the variables under debugging everything seems fine, but it keeps complaining the native missing..

**Comment by elect86** [comment]
Just tried to copy in the root project, because in the path there is also `.` and it works..

For some reasons the new `java.library.path` doesnt get loaded.

I literally copied the path I appended under `newJavaPath` and pasted in the explorer for the sake of god and it's correct, I get to the intended folder

sigh, 2018 and still dealing with this crap..

2018 and still dealing with this crap..

**Comment by Endolf** [comment]
This isn't an issue of the JInput code or packaging so closing.

**Comment by zdg-kinlon** [comment]
```kts
//...
implementation("net.java.jinput:jinput:2.0.10")
runtimeOnly("net.java.jinput:jinput-platform:2.0.7:natives-windows")
runtimeOnly("net.java.jinput:jinput-platform:2.0.7:natives-linux")
runtimeOnly("net.java.jinput:jinput-platform:2.0.7:natives-osx")
//...
```

I did it by extracting the native file from the jar file, placing it in the same folder as the compiled jar, and running it. If you need to develop in the IDE, you can put the local file in the root directory of the module, I directly put it in the root directory of the project and run it directly

![20241121203338](https://github.com/user-attachments/assets/770e3423-8f18-4e44-b759-75f66047c34a)
