### ISSUE TITLE
Found unknown windows version: Windows 8(.1)

### ISSUE THREAD

**Issue by Ravian2002** [jinput/jinput#3]
Can somebody please fix this 'issue'?
It's pretty irritating :þ.

**Comment by Endolf** [comment]
Can you confirm what version of JInput you are using?, what timestamp or md5sum is on the dll?

**Comment by Ravian2002** [comment]
On the DLL is the timestamp 21/5/2013 20:32

**Comment by Endolf** [comment]
Where did the version you have come from?, is it packaged with something else, or one you downloaded?.

**Comment by Ravian2002** [comment]
It was included with slick2D

**Comment by Endolf** [comment]
Hopefully fixed by commit 0943752c259d3964753dd0af12d0bd84bb42807d

**Comment by Endolf** [comment]
The jinput.jar in the latest build should fix it. http://ci.newdawnsoftware.com/job/JInput/2572/artifact/dist/

**Comment by Ravian2002** [comment]
There isn't changed any code... (I looked in it with a decompiler)

**Comment by Endolf** [comment]
Sorry, that jar is really old (2011), take the one from the nightly zip file, looks like I need to tweak the way the artifacts are produced. The jinput jar in the nightly zip file for any build since then should have a date stamp that is appropriate and should contain the change.

**Comment by Ravian2002** [comment]
Nothing changed when I downloaded the nightly zip from this build/page:
http://ci.newdawnsoftware.com/job/JInput/2575/artifact/dist/

**Comment by Endolf** [comment]
Just checking, you did unpack it and replace the jinput jar of the app you are testing with the one from the zip? :), I'm just surprised it's not working.

**Comment by Ravian2002** [comment]
Yes, but as I said before, no code changed :-1:

**Comment by Endolf** [comment]
Looks like the build farm has been misconfigured for a while. No-one seems to have noticed till now. The new jars appear to have the Windows 8 string in them so hopefully now it's up to date. Sorry about the confusion.

**Comment by Ravian2002** [comment]
It's fixed now.
Thnx!
