### ISSUE TITLE
Question: Is 32 Bit support dropped in version 2.0.9?

### ISSUE THREAD

**Issue by gurkenlabs** [jinput/jinput#43]
Hi there,

in the latest versions (>2.08), you changed the handling of the native libraries that are required to use `jinput`.

I'd like to update the [LITIengine](https://github.com/gurkenlabs/litiengine) to use the new version 2.0.9. It seems like the new version does only deploy the **x64** libraries though.

I miss the following natives when extracting the **jinput-2.0.9-natives-all.jar**:

* jinput-dx8.dll
* jinput-raw.dll
* libjinput-linux.so

Was the 32 Bit support dropped in the latest version? I couldn't find any explicit commit message or documentation about this.

Thank's in advance.

**Comment by Endolf** [comment]
As of 2.0.9 I'm no longer building 32 bit binaries, 32 bit JDKs are no longer supported, so JInput no longer supports 32 bit. That being said, the maven build should still work on 32 bit systems, so it should be possible to build it.
