### ISSUE TITLE
jinput-test.jar is missing from the natives-all.jar file?

### ISSUE THREAD

**Issue by WeavingBird1917** [jinput/jinput#55]
According to step 2 on the "Getting started with JInput" wiki page:

> Unpack the natives-all.jar file somewhere temporarily. You should get a dist folder, and in there,
> 
>     jinput-dx8.dll
>     jinput-raw.dll
>     jinput-test.jar
>     jinput-wintab.dll
>     jinput.jar
>     libjinput-linux.so
>     libjinput-osx.jnilib

I've followed the steps, however, upon unpacking the `natives-all.jar` file, I do not get a dist folder, nor the `jinput-test.jar` file. The` jinput.jar` has already been downloaded separately fro step 1. I've managed to get it working by manually downloading and compiling the tests.

**Comment by mporetvivint** [comment]
Same Issue here

**Comment by VickF** [comment]
Still true in 2020.  Where can we get the test classes?

**Comment by VickF** [comment]
> Still true in 2020. Where can we get the test classes?

OK - I see, as mentioned in the original comment, need to download the test classes manually from this git repo.

**Comment by VickF** [comment]
Closed, but did anything change?  
There's no jinput-test-<version>.jar.    
Should we change these instructions to match reality? 
https://github.com/jinput/jinput/wiki/Getting-started-with-JInput
