### ISSUE TITLE
Please review PR #56

### ISSUE THREAD

**Issue by seanidzenga** [jinput/jinput#58]
As per your suggestion I'm raising this PR to your attention, I have a mighty need to detect whether new controllers have been connected.

The PR is simple, we take the controller discovery out of `getControllers()` and place it in a publicly accessible `getNewControllers()` function. `getControllers()` calls `getNewControllers()` if the `controllers` list is empty. This is the best of both worlds, gives anyone using the library the ability to find new controllers manually and covers the concern you raised in #44 that `getControllers` is used in many people's input loop.

I'm open to renaming that method to `findNewControllers()` now that I'm thinking about it.

side-note: do you have @ mention notifications turned off?

**Comment by Endolf** [comment]
PR already raised, this issue is just extra noise.
