### ISSUE TITLE
How do I build Jinput?

### ISSUE THREAD

**Issue by mitch092** [jinput/jinput#65]
Hi, I wanted to apply a patch to jinput so I forked it. Then I did "mvn clean install" and I get: 
Could not resolve dependencies for project net.java.jinput:jinput:jar:2.0.10-SNAPSHOT: The following artifacts could not be resolved: net.java.jinput:windows-plugin:jar:natives-windows:2.0.10-SNAPSHOT......

How was this file generated?
https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.9/jinput-2.0.9.jar

I just need jinput-2.0.9.jar but with my patch applied, but I have no idea how this jar file was made. I'm new to maven, so apologies for the newbie question. The only other alternative is to decompile the class files or modify the bytecode, and that would be even less trivial than just building it.

**Comment by mitch092** [comment]
I'm just trying to figure out how this file was made:
https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.9/jinput-2.0.9.jar

I CD'd into the root of the jinput repo and ran "mvn clean install", and you're right, it failed to build the uberjar because the windows compiler isn't on my linux system.

But the file I linked above doesn't have the natives. And I don't need those, I just need to apply a small patch to that jar, but I can't because it only contains class files (which is why I'm trying to build from source).

Is the jinput-2.0.9.jar (mentioned on jinput's website, and also on maven central) the same as building the "applet" module in jinput? Or the "coreAPI" module? Or the "uberjar" module? I'm thinking it's the uberjar, right?

**Comment by hervegirod** [comment]
I had this problem and I created a fork on GitHub which used ang if you are interested

**Comment by mitch092** [comment]
Fork yours, apply my patch and build with apache ant? Ok, I'll try that.

**Comment by Endolf** [comment]
> I'm just trying to figure out how this file was made:
> https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.9/jinput-2.0.9.jar
> 
> I CD'd into the root of the jinput repo and ran "mvn clean install", and you're right, it failed to build the uberjar because the windows compiler isn't on my linux system.
> 
> But the file I linked above doesn't have the natives. And I don't need those, I just need to apply a small patch to that jar, but I can't because it only contains class files (which is why I'm trying to build from source).
> 
> Is the jinput-2.0.9.jar (mentioned on jinput's website, and also on maven central) the same as building the "applet" module in jinput? Or the "coreAPI" module? Or the "uberjar" module? I'm thinking it's the uberjar, right?

It's the uberjar, which does need all the plugins and natives. If you are just doing a local project, and don't need all the different platforms, you can run "mvn -am -pl plugins/linux clean install" and it will build the linux natives, the linux plugin and the core jar. The downside is that you'll need to either include the right jar files and .so files in the java library path.
