### ISSUE TITLE
Simulating Joystick Movement

### ISSUE THREAD

**Issue by vohratom** [jinput/jinput#70]
Hi there, I am so sorry for marking this question as an issue however, I did not find any other way how to get in touch with Endolf or simply anybody that could help me.

I need to simulate a very simple thing - joystick movement to the right - is it possible to do it with jinput? If so is there anybody that could create that piece of code for me? I am more than happy to pay for it.

Please reach me out via email tomas.vohradnik@gmail.com

Thank you and sorry once again!

**Comment by Endolf** [comment]
If you are using software that uses JInput it would be possible to write a plugin that simulates a joystick, but otherwise JInput is used to read real hardware, not be a virtual OS level driver.

**Comment by Endolf** [comment]
Hi
Not quite, JInput has a plugin system, which is automatically loads the platform specific native plugins (linux, mac, windows etc), but this is just the default behaviour, it can be overridden to load a different plugin. These plugins normally interface with the native libraries for handling input, like the evdev interface under linux or directx under windows. It is possible for someone to write a plugin for anything they wish, as long as it meets the published interface, JInput will query the loaded plugins and return any devices the plugin exposes. Someone could write a plugin that allows the values to set using API calls, and would then return those values to JInput. This would only work for games or other Java programs that use JInput to read input devices though.

**Comment by vohratom** [comment]
I see so in short it's not as easy as I was thinking it will be, right?

Thanks for the reply tho!
