### ISSUE TITLE
"Mode" not available

### ISSUE THREAD

**Issue by frizman21** [jinput/jinput#77]
I'm using a [Logitech X52](https://www.amazon.com/Logitech-X52-Flight-Contol-System/dp/B07QXPQRYX/ref=sr_1_1?crid=2NY18K0MPEZMD&keywords=X52&qid=1674920952&sprefix=x52%2Caps%2C94&sr=8-1&th=1). The silver knob towards the top of controller is called the "Mode". This input is shown below:

![image](https://user-images.githubusercontent.com/11731079/215276058-91ec9d76-8a2d-4b1a-8e04-53276742464a.png)

I don't receive any callbacks when this knob is changed. Is it available elsewhere in the API? Please advise.

A thank you for this library!

**Comment by Endolf** [comment]
What does the jinput text test show?, can you try setting the` jinput.loglevel` property to info or even debug and see what falls out?
